groups:
  - name: ((user))
    jobs:
      - push
      - scale-out
      - scale-in

resources:
  - name: app
    type: git
    source:
      uri: https://github.com/gerhard/pipeline
      branch: master
      paths:
        - "slides"

  - name: paas
    type: cf
    source:
      api: ((cf_api))
      organization: ((cf_org))
      password: ((cf_pass))
      space: ((cf_space))
      username: ((cf_user))

  - name: morning
    type: time
    source:
      start: 9:00 AM
      stop: 9:10 AM
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]

  - name: evening
    type: time
    source:
      start: 6:00 PM
      stop: 6:10 PM
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]


jobs:
  - name: push
    serial: true
    serial_groups:
      - app
    plan:
      - get: app
        trigger: true
      - put: paas
        params:
          manifest: app/slides/manifest.yml
          current_app_name: pipeline

  - name: scale-out
    serial: true
    serial_groups:
      - app
    plan:
      - get: app
      - get: morning
        trigger: true
      - task: make-scale
        file: app/slides/ci/make.yml
        params:
          TARGET: scale
          INSTANCES: 10
          CF_API: ((cf_api))
          CF_ORG: ((cf_org))
          CF_PASS: ((cf_pass))
          CF_SPACE: ((cf_space))
          CF_USER: ((cf_user))

  - name: scale-in
    serial: true
    serial_groups:
      - app
    plan:
      - get: app
      - get: evening
        trigger: true
      - task: make-scale
        file: app/slides/ci/make.yml
        params:
          TARGET: scale
          INSTANCES: 2
          CF_API: ((cf_api))
          CF_ORG: ((cf_org))
          CF_PASS: ((cf_pass))
          CF_SPACE: ((cf_space))
          CF_USER: ((cf_user))
