groups:
  - name: ((user))
    jobs:
      - deploy

resources:
  - name: app
    type: git
    source:
      uri: https://github.com/gerhard/pipeline
      branch: master
      paths:
        - "slides"

jobs:
  - name: deploy
    plan:
      - get: app
      - task: make-public
        file: app/slides/ci/make.yml
        params:
          CF_API: ((cf_api))
          CF_ORG: ((cf_org))
          CF_PASS: ((cf_pass))
          CF_SPACE: ((cf_space))
          CF_USER: ((cf_user))
